export interface RouteDefinition {
  id: string;
  name: string;
}

export interface GameDefinition {
  id: string;
  name: string;
  subtitle: string;
}

export const GAMES: GameDefinition[] = [
  {
    id: "firered-leafgreen",
    name: "FireRed / LeafGreen",
    subtitle: "Kanto, Gen III",
  },
  {
    id: "emerald",
    name: "Emerald",
    subtitle: "Hoenn, Gen III",
  },
  {
    id: "platinum",
    name: "Platinum",
    subtitle: "Sinnoh, Gen IV",
  },
  {
    id: "black-white",
    name: "Black / White",
    subtitle: "Unova, Gen V",
  },
];

export const ROUTES_BY_GAME: Record<string, RouteDefinition[]> = {
  "firered-leafgreen": [
    { id: "route-1", name: "Route 1" },
    { id: "route-2", name: "Route 2" },
    { id: "viridian-forest", name: "Viridian Forest" },
    { id: "route-3", name: "Route 3" },
    { id: "mt-moon", name: "Mt. Moon" },
    { id: "route-4", name: "Route 4" },
    { id: "route-24", name: "Route 24" },
    { id: "route-25", name: "Route 25" },
    { id: "route-5", name: "Route 5" },
    { id: "route-6", name: "Route 6" },
    { id: "ss-anne", name: "S.S. Anne" },
    { id: "digletts-cave", name: "Diglett's Cave" },
    { id: "route-11", name: "Route 11" },
    { id: "route-9", name: "Route 9" },
    { id: "rock-tunnel", name: "Rock Tunnel" },
    { id: "route-10", name: "Route 10" },
    { id: "pokemon-tower", name: "Pokemon Tower" },
    { id: "route-8", name: "Route 8" },
    { id: "route-7", name: "Route 7" },
    { id: "route-12", name: "Route 12" },
    { id: "route-13", name: "Route 13" },
    { id: "route-14", name: "Route 14" },
    { id: "route-15", name: "Route 15" },
    { id: "route-16", name: "Route 16" },
    { id: "route-17", name: "Route 17" },
    { id: "route-18", name: "Route 18" },
    { id: "fuchsia-safari-zone", name: "Safari Zone" },
    { id: "power-plant", name: "Power Plant" },
    { id: "route-19", name: "Route 19" },
    { id: "route-20", name: "Route 20" },
    { id: "seafoam-islands", name: "Seafoam Islands" },
    { id: "pokemon-mansion", name: "Pokemon Mansion" },
    { id: "route-21", name: "Route 21" },
    { id: "route-22", name: "Route 22" },
    { id: "route-23", name: "Route 23" },
    { id: "victory-road-kanto", name: "Victory Road" },
    { id: "cerulean-cave", name: "Cerulean Cave" },
  ],
  emerald: [
    { id: "route-101", name: "Route 101" },
    { id: "route-102", name: "Route 102" },
    { id: "route-103", name: "Route 103" },
    { id: "route-104", name: "Route 104" },
    { id: "petalburg-woods", name: "Petalburg Woods" },
    { id: "route-116", name: "Route 116" },
    { id: "rusturf-tunnel", name: "Rusturf Tunnel" },
    { id: "route-105", name: "Route 105" },
    { id: "route-106", name: "Route 106" },
    { id: "granite-cave", name: "Granite Cave" },
    { id: "route-107", name: "Route 107" },
    { id: "route-108", name: "Route 108" },
    { id: "route-109", name: "Route 109" },
    { id: "route-110", name: "Route 110" },
    { id: "new-mauville", name: "New Mauville" },
    { id: "route-117", name: "Route 117" },
    { id: "route-111", name: "Route 111" },
    { id: "hoenn-desert", name: "Desert" },
    { id: "route-112", name: "Route 112" },
    { id: "fiery-path", name: "Fiery Path" },
    { id: "route-113", name: "Route 113" },
    { id: "route-114", name: "Route 114" },
    { id: "meteor-falls", name: "Meteor Falls" },
    { id: "jagged-pass", name: "Jagged Pass" },
    { id: "route-115", name: "Route 115" },
    { id: "route-118", name: "Route 118" },
    { id: "route-119", name: "Route 119" },
    { id: "route-120", name: "Route 120" },
    { id: "route-121", name: "Route 121" },
    { id: "hoenn-safari-zone", name: "Safari Zone" },
    { id: "mt-pyre", name: "Mt. Pyre" },
    { id: "route-122", name: "Route 122" },
    { id: "route-123", name: "Route 123" },
    { id: "route-124", name: "Route 124" },
    { id: "shoal-cave", name: "Shoal Cave" },
    { id: "route-125", name: "Route 125" },
    { id: "route-126", name: "Route 126" },
    { id: "route-127", name: "Route 127" },
    { id: "route-128", name: "Route 128" },
    { id: "seafloor-cavern", name: "Seafloor Cavern" },
    { id: "route-129", name: "Route 129" },
    { id: "route-130", name: "Route 130" },
    { id: "route-131", name: "Route 131" },
    { id: "sky-pillar", name: "Sky Pillar" },
    { id: "route-132", name: "Route 132" },
    { id: "route-133", name: "Route 133" },
    { id: "route-134", name: "Route 134" },
    { id: "victory-road-hoenn", name: "Victory Road" },
    { id: "cave-of-origin", name: "Cave of Origin" },
    { id: "abandoned-ship", name: "Abandoned Ship" },
  ],
  platinum: [
    { id: "route-201", name: "Route 201" },
    { id: "route-202", name: "Route 202" },
    { id: "route-203", name: "Route 203" },
    { id: "oreburgh-gate", name: "Oreburgh Gate" },
    { id: "oreburgh-mine", name: "Oreburgh Mine" },
    { id: "route-204", name: "Route 204" },
    { id: "ravaged-path", name: "Ravaged Path" },
    { id: "floaroma-meadow", name: "Floaroma Meadow" },
    { id: "valley-windworks", name: "Valley Windworks" },
    { id: "route-205", name: "Route 205" },
    { id: "eterna-forest", name: "Eterna Forest" },
    { id: "old-chateau", name: "Old Chateau" },
    { id: "route-206", name: "Route 206" },
    { id: "wayward-cave", name: "Wayward Cave" },
    { id: "mt-coronet", name: "Mt. Coronet" },
    { id: "route-207", name: "Route 207" },
    { id: "route-208", name: "Route 208" },
    { id: "route-209", name: "Route 209" },
    { id: "lost-tower", name: "Lost Tower" },
    { id: "solaceon-ruins", name: "Solaceon Ruins" },
    { id: "route-210", name: "Route 210" },
    { id: "route-211", name: "Route 211" },
    { id: "route-212", name: "Route 212" },
    { id: "trophy-garden", name: "Trophy Garden" },
    { id: "great-marsh", name: "Great Marsh" },
    { id: "route-213", name: "Route 213" },
    { id: "valor-lakefront", name: "Valor Lakefront" },
    { id: "route-214", name: "Route 214" },
    { id: "route-215", name: "Route 215" },
    { id: "route-216", name: "Route 216" },
    { id: "route-217", name: "Route 217" },
    { id: "acuity-lakefront", name: "Acuity Lakefront" },
    { id: "route-218", name: "Route 218" },
    { id: "fuego-ironworks", name: "Fuego Ironworks" },
    { id: "route-219", name: "Route 219" },
    { id: "route-220", name: "Route 220" },
    { id: "route-221", name: "Route 221" },
    { id: "route-222", name: "Route 222" },
    { id: "route-223", name: "Route 223" },
    { id: "route-224", name: "Route 224" },
    { id: "victory-road-sinnoh", name: "Victory Road" },
    { id: "route-225", name: "Route 225" },
    { id: "route-226", name: "Route 226" },
    { id: "route-227", name: "Route 227" },
    { id: "stark-mountain", name: "Stark Mountain" },
    { id: "route-228", name: "Route 228" },
    { id: "route-229", name: "Route 229" },
    { id: "route-230", name: "Route 230" },
    { id: "iron-island", name: "Iron Island" },
  ],
  "black-white": [
    { id: "route-1", name: "Route 1" },
    { id: "route-2", name: "Route 2" },
    { id: "dreamyard", name: "Dreamyard" },
    { id: "route-3", name: "Route 3" },
    { id: "wellspring-cave", name: "Wellspring Cave" },
    { id: "pinwheel-forest", name: "Pinwheel Forest" },
    { id: "route-4", name: "Route 4" },
    { id: "desert-resort", name: "Desert Resort" },
    { id: "relic-castle", name: "Relic Castle" },
    { id: "route-5", name: "Route 5" },
    { id: "driftveil-drawbridge", name: "Driftveil Drawbridge" },
    { id: "cold-storage", name: "Cold Storage" },
    { id: "route-6", name: "Route 6" },
    { id: "chargestone-cave", name: "Chargestone Cave" },
    { id: "mistralton-cave", name: "Mistralton Cave" },
    { id: "route-7", name: "Route 7" },
    { id: "celestial-tower", name: "Celestial Tower" },
    { id: "twist-mountain", name: "Twist Mountain" },
    { id: "dragonspiral-tower", name: "Dragonspiral Tower" },
    { id: "route-8", name: "Route 8" },
    { id: "moor-of-icirrus", name: "Moor of Icirrus" },
    { id: "route-9", name: "Route 9" },
    { id: "tubeline-bridge", name: "Tubeline Bridge" },
    { id: "route-10", name: "Route 10" },
    { id: "victory-road-unova", name: "Victory Road" },
    { id: "route-11", name: "Route 11" },
    { id: "route-12", name: "Route 12" },
    { id: "village-bridge", name: "Village Bridge" },
    { id: "route-13", name: "Route 13" },
    { id: "abundant-shrine", name: "Abundant Shrine" },
    { id: "route-14", name: "Route 14" },
    { id: "route-15", name: "Route 15" },
    { id: "marvelous-bridge", name: "Marvelous Bridge" },
    { id: "route-16", name: "Route 16" },
    { id: "lostlorn-forest", name: "Lostlorn Forest" },
    { id: "route-17", name: "Route 17" },
    { id: "route-18", name: "Route 18" },
    { id: "giant-chasm", name: "Giant Chasm" },
  ],
};

export function getGameById(gameId: string): GameDefinition | undefined {
  return GAMES.find((game) => game.id === gameId);
}

export function getRoutesForGame(gameId: string): RouteDefinition[] {
  return ROUTES_BY_GAME[gameId] ?? [];
}
